CREATE TABLE `db_hachimaro_order_master`.`product` (
  `id` INT(11) NOT NULL COMMENT '管理用ID',
  `category` INT(11) NOT NULL COMMENT '1:アルコール2:ソフトドリンク3:お菓子',
  `name` VARCHAR (50) NOT NULL COMMENT '商品名',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '生成時間',
  `delete_time` DATETIME NULL DEFAULT NULL COMMENT '削除時間',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品情報';

CREATE TABLE `db_hachimaro_order_master`.`seat` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '管理用ID',
  `m_store_id` INT(10) UNSIGNED NOT NULL COMMENT '店ごとのユニークなID',
  `m_seat_id` INT(10) UNSIGNED NOT NULL COMMENT '座席ID',
  `seat_group_id` INT(10) UNSIGNED NOT NULL COMMENT 'ボックス席等の場合同一の値',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '生成時間',
  `delete_time` DATETIME NULL DEFAULT NULL COMMENT '削除時間',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '座席管理用マスタ';
